name: 'CI Deploy Tools'
description: 'Collection of ci/cd deploy tools'
inputs:
  args:
    description: 'Cmd and args'
    required: true
    default: '-h'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}